ccea:
  evaluation:
    multi_rollout:
      num_rollouts: 1
  mutation:
    independent_probability: 0.5
    mean: 0.0
    std_deviation: 0.1
  network:
    hidden_layers:
    - 15
    rover_max_velocity: 1.0
    uav_max_velocity: 1.0
  num_generations: 100
  num_steps: 30
  populations:
    agent_population_size: 25
  selection:
    n_elites_binary_tournament:
      n_individual_elites: 5
      n_team_elites: 5
  team_formation:
    type: softmax_teams
  weight_initialization:
    lower_bound: -0.5
    upper_bound: 0.5
data:
  checkpoints:
    delete_previous: true
    frequency: 1
    save: true
  save_trajectories:
    test:
      num_gens_between_save: 1
      switch: true
    train:
      num_gens_between_save: 10
      switch: false
debug:
  random_seed:
    increment_every_trial: true
    set_seed: 0
  reward_equals_G: false
env:
  agents:
    rovers:
    - IndirectDifference:
        assignment: automatic
        automatic:
          credit: AllOrNothing
          timescale: timestep
        manual: []
        type: removal
      action:
        type: dxdy
      needs_uav_to_move: true
      observation_radius: 2.0
      policy:
        type: network
      position:
        fixed:
        - 5.0
        - 10.0
        spawn_rule: fixed
      resolution: 90
      reward_type: IndirectDifference
      sensor:
        accum_type: sum
        type: SmartLidar
    uavs:
    - IndirectDifference:
        assignment: automatic
        automatic:
          credit: AllOrNothing
          timescale: timestep
        manual: []
        type: removal
      action:
        type: dxdy
      bounds:
        high_x: 20
        high_y: 20
        low_x: 0
        low_y: 0
      observation_radius: 100.0
      position:
        fixed:
        - 5.0
        - 10.0
        spawn_rule: fixed
      resolution: 90
      reward_type: IndirectDifference
    - IndirectDifference:
        assignment: automatic
        automatic:
          credit: AllOrNothing
          timescale: timestep
        manual: []
        type: removal
      action:
        type: dxdy
      bounds:
        high_x: 40
        high_y: 20
        low_x: 20
        low_y: 0
      observation_radius: 100.0
      position:
        fixed:
        - 25.0
        - 10.0
        spawn_rule: fixed
      resolution: 90
      reward_type: IndirectDifference
  map_size:
  - 40.0
  - 20.0
  pois:
    hidden_pois:
    - capture_radius: 50.0
      constraint: sequential
      coupling: 1
      disappear_bool: true
      observation_radius: 5.0
      position:
        fixed:
        - 15
        - 2.5
        spawn_rule: fixed
      value: 1.0
    - capture_radius: 50.0
      constraint: sequential
      coupling: 1
      disappear_bool: true
      observation_radius: 5.0
      position:
        fixed:
        - 35
        - 2.5
        spawn_rule: fixed
      value: 1.0
    rover_pois: []
experiment:
  num_trials: 1
processing:
  num_threads: 15
  use_multiprocessing: true
